# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZallData' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#  pod 'ZallDataSDK', :path=>'../../'
#  pod 'ZallDataSDK/Location', :path=>'../../'
  pod 'ZallDataSDK/All', :path=>'../../'
  

  # Pods for ZallData
  
end

target 'ZallDataExtention' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'ZallDataSDK/Extension', :path=>'../../'

  
  # Pods for ZallDataExtention

end

target 'ZallDataSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ZallDataSDK/All', :path=>'../../'

  # Pods for ZallDataSwift

end
